### ISSUE TITLE
Guavaを使わない方が良くないですか？

### ISSUE THREAD

**Issue by kenchan1837** [studyplus/Studyplus-Android-SDK#9]
Guavaは大きいライブラリなので、pro-guardを通さないと、dex 64k問題が発生しやすい。
Android Studioではなく、Eclipseで開発している場合だと、毎回pro-guardを通すのは非常に手間。
EclipseでAndroidを開発する人達もまだまだ多いので、Guavaに依存しない方が組み込みやすいです。

**Comment by kanekoteruaki** [comment]
すいません。確認させていただきたいのですが、
guava-18.0.jarはもう削除して大丈夫な状況でしょうか？

**Comment by kanekoteruaki** [comment]
その後いかがでしょうか？

**Comment by Suki-VT** [comment]
Hi there,
please do not use guava in sdk, it is not necessary, it make project filed in kotlin language andhigher api level, eventbus is convenience but not necessary, please use interface instead.

**Comment by nabesuke0** [comment]
Androidアプリ担当です。
長らくメンテをしておらず大変申し訳ありません。
いまguava廃止 + リプレースで動き出しましたのでもう暫くお待ち下さい。

**Comment by nabesuke0** [comment]
こちらにversion2を公開しております。こちらをご使用ください。
https://github.com/studyplus/Studyplus-Android-SDK-V2

**Comment by koji-1009** [comment]
SDK ver1系は開発を凍結したため、チケットをクローズします。
